apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-chatbot-deployment
  namespace: staging
  labels:
    app: llmops-chatbot
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops-chatbot
  template:
    metadata:
      labels:
        app: llmops-chatbot
        environment: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: chatbot
          image: YOUR_ECR_URI:staging-latest  # Updated by CI/CD
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: chatbot-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
