apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
type: Opaque
stringData:
  S3_BUCKET_NAME: "llmops-knowledge-base"
  S3_FAISS_PREFIX: "faiss_index"
  HUGGINGFACEHUB_API_TOKEN: "hf_yourtoken"  # ⚠️ REPLACE with actual HF token from Step 2.1
  DYNAMODB_FEEDBACK_TABLE: "llmops-feedback-log"


