apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-chatbot-deployment
  namespace: production
  labels:
    app: llmops-chatbot
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: llmops-chatbot
  template:
    metadata:
      labels:
        app: llmops-chatbot
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: chatbot
          image: YOUR_ECR_URI:production-latest  # Updated by CI/CD
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: chatbot-secrets
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
